# Copyright 2017 The Rust Project Developers. See the COPYRIGHT
# file at the top-level directory of this distribution and at
# http://rust-lang.org/COPYRIGHT.
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

set -ex

# This file was generated with https://github.com/richfelker/musl-cross-make and
# http://www.nongnu.org/libunwind/. The cross compiler in the sysroot was
# compiled by an x86_64 cross toolchain, also generated by musl-cross-make. Then
# libunwind 1.2.1 (built by this MIPS cross toolchain) was added to the sysroot.
URL="https://s3.amazonaws.com/rust-lang-ci/rust-ci-mirror"
FILE="2017-07-11-sysroot-mips.tar.xz"
curl -L "$URL/$FILE" | tar xJf - -C /usr/local
